apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: trafficsplits.split.smi-spec.io
spec:
  group: split.smi-spec.io
  scope: Namespaced
status:
  acceptedNames:
    kind: TrafficSplit
    listKind: TrafficSplitList
    plural: trafficsplits
    singular: trafficsplit
    shortNames:
      - ts
