apiVersion: v1
kind: Namespace
metadata:
  name: kuttl-test-stage
  annotations: 
    'linkerd.io/inject': 'enabled'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-a-deployment
  namespace: kuttl-test-stage
  labels:
    app: app-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-a
  template:
    metadata:
      labels:
        app: app-a
    spec:
      containers:
      - name: app-a
        image: layer5/learn-layer5:latest
        ports:
        - containerPort: 9091
          name: http
        env:
        - name: SERVICE_NAME
          value: "app-a"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-b-deployment
  namespace: kuttl-test-stage
  labels:
    app: app
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
      version: v1
  template:
    metadata:
      labels:
        app: app
        version: v1
    spec:
      containers:
      - name: app-b
        image: layer5/learn-layer5:latest
        ports:
        - containerPort: 9091
          name: http
          protocol: TCP
        env:
        - name: SERVICE_NAME
          value: "app-b"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-c-deployment
  namespace: kuttl-test-stage
  labels:
      app: app
      version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
      version: v2
  template:
    metadata:
      labels:
        app: app
        version: v2
    spec:
      containers:
      - name: app-c
        image: layer5/learn-layer5:latest
        ports:
        - containerPort: 9091
          name: http
          protocol: TCP
        env:
        - name: SERVICE_NAME
          value: "app-c"
---
apiVersion: v1
kind: Service
metadata:
  name: app-v1
  namespace: kuttl-test-stage
spec:
  type: NodePort
  selector:
    app: app
    version: v1
  ports:
  - name: http
    protocol: TCP
    port: 9091
    targetPort: 9091
---
apiVersion: v1
kind: Service
metadata:
  name: app-v2
  namespace: kuttl-test-stage
spec:
  type: NodePort
  selector:
    app: app
    version: v2
  ports:
  - name: http
    protocol: TCP
    port: 9091
    targetPort: 9091
---
apiVersion: v1
kind: Service
metadata:
  name: app-svc
  namespace: kuttl-test-stage
spec:
  type: NodePort
  selector:
    app: app
  ports:
  - name: http
    protocol: TCP
    port: 9091
    targetPort: 9091

# for i in {1..20};do curl app-svc.kuttl-test-stage.svc.cluster.local.:9091/echo; echo; done
# curl app-v1.kuttl-test-stage.svc.cluster.local.:9091/metrics
# curl -X "DELETE" app-v1.kuttl-test-stage.svc.cluster.local.:9091/metrics