---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-a
  labels:
    app: app-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-a
  template:
    metadata:
      # annotations:
      #   'consul.hashicorp.com/connect-inject': 'true'
      labels:
        app: app-a
    
    spec:
      # serviceAccountName: service-a
      # automountServiceAccountToken: true
      containers:
      - name: app-a
        image: layer5/sample-app-service:dev
        imagePullPolicy: Never
        ports:
        - containerPort: 9091
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-b
  labels:
    app: app-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-b
  template:
    metadata:
      labels:
        app: app-b
      # annotations:
      #   'consul.hashicorp.com/connect-inject': 'true'
    spec:
      # serviceAccountName: service-b
      # automountServiceAccountToken: true
      containers:
      - name: app-b
        image: layer5/sample-app-service:dev
        imagePullPolicy: Never
        ports:
        - containerPort: 9091
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-c
  labels:
    app: app-c
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-c
  template:
    metadata:
      labels:
        app: app-c
      # annotations:
      #   'consul.hashicorp.com/connect-inject': 'true'
    spec:
      # serviceAccountName: service-c
      # automountServiceAccountToken: true
      containers:
      - name: app-c
        image: layer5/sample-app-service:dev
        imagePullPolicy: Never
        ports:
        - containerPort: 9091
---
apiVersion: v1
kind: Service
metadata:
  name: service-a
spec:
  type: NodePort
  selector:
    app: app-a
  ports:
  - name: http
    protocol: TCP
    port: 9091
    targetPort: 9091
---
apiVersion: v1
kind: Service
metadata:
  name: service-b
spec:
  type: NodePort
  selector:
    app: app-b
  ports:
  - name: http
    protocol: TCP
    port: 9091
    targetPort: 9091
---
apiVersion: v1
kind: Service
metadata:
  name: service-c
spec:
  type: NodePort
  selector:
    app: app-c
  ports:
  - name: http
    protocol: TCP
    port: 9091
    targetPort: 9091
