apiVersion: v1
kind: Namespace
metadata:
  name: kuttl-test-stage
  annotations: 
    'linkerd.io/inject': 'enabled'
---
apiVersion: v1
kind: Service
metadata:
  name: app-b
  namespace: kuttl-test-stage
spec:
  type: NodePort
  selector:
    app: app
    version: b
  ports:
  - name: http
    protocol: TCP
    port: 9091
    targetPort: 9091
---
apiVersion: v1
kind: Service
metadata:
  name: app-c
  namespace: kuttl-test-stage
spec:
  type: NodePort
  selector:
    app: app
    version: c
  ports:
  - name: http
    protocol: TCP
    port: 9091
    targetPort: 9091
---
apiVersion: v1
kind: Service
metadata:
  name: app-svc
  namespace: kuttl-test-stage
spec:
  type: NodePort
  selector:
    app: app
  ports:
  - name: http
    protocol: TCP
    port: 9091
    targetPort: 9091
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-a-deployment
  namespace: kuttl-test-stage
status:
  readyReplicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-b-deployment
  namespace: kuttl-test-stage
status:
  readyReplicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-c-deployment
  namespace: kuttl-test-stage
status:
  readyReplicas: 1