apiVersion: v1
kind: Namespace
metadata:
  name: kuttl-test-stage
  annotations: 
    'linkerd.io/inject': 'enabled'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-a-deployment
  namespace: kuttl-test-stage
  labels:
    app: app-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-a
  template:
    metadata:
      labels:
        app: app-a
    spec:
      containers:
      - name: app-a
        image: layer5/learn-layer5:latest
        ports:
        - containerPort: 9091
          name: http
        env:
        - name: SERVICE_NAME
          value: "app-a"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-b-deployment
  namespace: kuttl-test-stage
  labels:
    app: app
    version: b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
      version: b
  template:
    metadata:
      labels:
        app: app
        version: b
    spec:
      containers:
      - name: app-b
        image: layer5/learn-layer5:latest
        ports:
        - containerPort: 9091
          name: http
          protocol: TCP
        env:
        - name: SERVICE_NAME
          value: "app-b"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-c-deployment
  namespace: kuttl-test-stage
  labels:
      app: app
      version: c
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
      version: c
  template:
    metadata:
      labels:
        app: app
        version: c
    spec:
      containers:
      - name: app-c
        image: layer5/learn-layer5:latest
        ports:
        - containerPort: 9091
          name: http
          protocol: TCP
        env:
        - name: SERVICE_NAME
          value: "app-c"
---
apiVersion: v1
kind: Service
metadata:
  name: app-a
  namespace: kuttl-test-stage
spec:
  type: NodePort
  selector:
    app: app-a
  ports:
  - name: http
    protocol: TCP
    port: 9091
    targetPort: 9091
---
apiVersion: v1
kind: Service
metadata:
  name: app-b
  namespace: kuttl-test-stage
spec:
  type: NodePort
  selector:
    app: app
    version: b
  ports:
  - name: http
    protocol: TCP
    port: 9091
    targetPort: 9091
---
apiVersion: v1
kind: Service
metadata:
  name: app-c
  namespace: kuttl-test-stage
spec:
  type: NodePort
  selector:
    app: app
    version: c
  ports:
  - name: http
    protocol: TCP
    port: 9091
    targetPort: 9091
---
apiVersion: v1
kind: Service
metadata:
  name: app-svc
  namespace: kuttl-test-stage
spec:
  type: NodePort
  selector:
    app: app
  ports:
  - name: http
    protocol: TCP
    port: 9091
    targetPort: 9091