apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-a
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-b
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-c
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-a-deployment
status:
  readyReplicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-b-deployment
status:
  readyReplicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-c-deployment
status:
  readyReplicas: 1
---
apiVersion: v1
kind: Service
metadata:
  name: app-a
spec:
  type: NodePort
  selector:
    app: app-a
  ports:
  - name: http
    protocol: TCP
    port: 9091
    # targetPort: 9091
---
apiVersion: v1
kind: Service
metadata:
  name: app-b
spec:
  type: NodePort
  selector:
    app: app-b
  ports:
  - name: http
    protocol: TCP
    port: 9091
    # targetPort: 9091
---
apiVersion: v1
kind: Service
metadata:
  name: app-c
spec:
  type: NodePort
  selector:
    app: app-c
  ports:
  - name: http
    protocol: TCP
    port: 9091
    # targetPort: 9091