# TCPRoute for Counting Service
---
apiVersion: specs.smi-spec.io/v1alpha1
kind: TCPRoute
metadata:
  name: service-tcp-route
  namespace: kuttl-test-stage

# TrafficTarget defines allowed routes for service-a
# In this example service-a is allowed to connect using
# TCP
---
apiVersion: access.smi-spec.io/v1alpha1
kind: TrafficTarget
metadata:
  name: service-targets
  namespace: kuttl-test-stage
  # namespace: default
destination:
  kind: ServiceAccount
  name: service-b
  namespace: kuttl-test-stage
  # namespace: default
sources:
- kind: ServiceAccount
  name: service-a
  namespace: kuttl-test-stage
  # namespace: default
specs:
- kind: TCPRoute
  name: service-tcp-route