apiVersion: specs.smi-spec.io/v1alpha1
kind: TCPRoute
metadata:
  name: service-tcp-route
  namespace: <NAMESPACE>
---
apiVersion: access.smi-spec.io/v1alpha1
kind: TrafficTarget
metadata:
  name: service-targets
  namespace: <NAMESPACE>
destination:
  kind: ServiceAccount
  name: service-b
  namespace: <NAMESPACE>
sources:
- kind: ServiceAccount
  name: service-a
  namespace: <NAMESPACE>
specs:
- kind: TCPRoute
  name: service-tcp-route