apiVersion: kudo.dev/v1alpha1
kind: TestStep
delete:
- apiVersion: specs.smi-spec.io/v1alpha1
  kind: TCPRoute
  name: service-tcp-route
  namespace: kuttl-test-stage
- apiVersion: access.smi-spec.io/v1alpha1
  kind: TrafficTarget
  name: service-targets
  namespace: kuttl-test-stage