apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: httproutegroups.specs.smi-spec.io
spec:
  group: specs.smi-spec.io
  scope: Namespaced
status:
  acceptedNames:
    kind: HTTPRouteGroup
    shortNames: 
      - htr
    plural: httproutegroups
    singular: httproutegroup

---

apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: tcproutes.specs.smi-spec.io
spec:
  group: specs.smi-spec.io
  scope: Namespaced
status:
  acceptedNames:
    kind: TCPRoute
    shortNames: 
      - tr
    plural: tcproutes
    singular: tcproute

